room:
  address: ":9000"

message:
  address: ":9001"
  ttl: 10m

session:
  address: ":9002"
  ttl: 10m

cassandra:
  addresses: localhost
  port: 9042
  username: cassandra
  password: cassandra
  keyspace: shinfo

redis:
  address: localhost:6379
  database: 0

logging:
  json: true
  level: -1
